### ISSUE TITLE
Migrate font-size from px to rem

### ISSUE THREAD

**Issue by aleksey-hoffman** [aleksey-hoffman/sigma-file-manager#327]
Ref:
https://www.seeratawan.me/blog/why-you-should-move-from-px-to-rem-in-css

This will make it possible to scale fonts globally:

```css
html {
  font-size: 120%;
}
```
